services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: calendar-backend
    ports:
      - "3000:3001"
    volumes:
      - calendar-data:/app/data
      - calendar-logs:/app/logs
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - calendar-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://192.168.42.106:3000}
    container_name: calendar-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - calendar-network

networks:
  calendar-network:
    driver: bridge

volumes:
  calendar-data:
  calendar-logs: