version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: calendar-backend
    ports:
      - "3000:3001"
    volumes:
      - ./backend/calendar.db:/app/calendar.db
      - ./backend/logs:/app/logs
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - calendar-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: calendar-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - calendar-network

networks:
  calendar-network:
    driver: bridge

volumes:
  calendar-data:
  calendar-logs: